services:
  keycloak:
    container_name: wlcg-keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    platform: linux/amd64
    command: start-dev --health-enabled=true --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      retries: 20
      start_period: 30s
    networks:
      - wlcg-net

networks:
  wlcg-net:
    driver: bridge